name: cs ci pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: restore dependencies
      run: |
        dotnet restore ./prime/prime.csproj
        dotnet restore ./primetest/test.csproj

    - name: build 
      run: |
        dotnet build ./prime/prime.csproj --no-restore
        dotnet build ./primetest/test.csproj --no-restore

    - name: run tests
      run: |
        dotnet test ./primetest/test.csproj --no-build --verbosity normal
